### ISSUE TITLE
What should we provide as output of the identity verification

### ISSUE THREAD

**Issue by juliette-ubbleai** [ubbleai/discussions#10]
Hello,

As an input of our product discussion this afternoon, please find attached a word document presenting what Gemalto provides to Telefonica Germany after a verification (Valerie Annexe 1)
I also attach Gemalto standard product proposal, where you will find example of PDF reports that we sent to our customers. (Template ID Verification MNO)

[Template ID Verification MNOs Commercial Proposal V1.8.docx](https://github.com/ubbleai/discussions/files/2053319/Template.ID.Verification.MNOs.Commercial.Proposal.V1.8.docx)

[Valerie_Annex 1_Service_Description_Gemalto_180209_final clean.docx](https://github.com/ubbleai/discussions/files/2053248/Valerie_Annex.1_Service_Description_Gemalto_180209_final.clean.docx)

**Comment by ndeber** [comment]
Output of discussion, here is the structure of what we send to our clients:
[https://drive.google.com/drive/u/0/folders/1YzHMWf5HqiIgsfDQu0B4UodcioZuyNn4](url)

Here is the list of identified frauds (3 categories):
[https://drive.google.com/drive/folders/1YzHMWf5HqiIgsfDQu0B4UodcioZuyNn4](url)
