### ISSUE TITLE
What is the minimum we should have in MVP for RGPD compliance

### ISSUE THREAD

**Issue by juliette-ubbleai** [ubbleai/discussions#2]
Synthese des traitements et de ce qui doit etre fait :
https://docs.google.com/document/d/1wZ2YiELlW6-_k95T2ZWMgoeGj-2u9zDunA1FyF_Xuio/edit
@ndeber @francoiswyss

**Comment by juliette-ubbleai** [comment]
Nous avons discuté avec Seraphin aujourd'hui, etait présent le CEO (Thomas de Saint Aubin) et une juriste experte RGPD (Anais). Je leur avais partagé le brief, qui leur avait semblé clair. Ils l'avaient lu, et avaient compris notre business.

Thomas est aussi président co-fondateur de la privacy-tech, leur credo etant : les startup de la tech devraient voir la RGPD comme une opportunité business. Il nous invite à nous différencier sur le sujet, tout en étant pro-business - il ne nous pousse pas à être compliant à 100%. Thomas a bossé pour France connect.
 
Seraphin a une triple expertise : Legal (avec un pole privacy) + tech + startup
Ils sont très intégré dans l'écosystème tech parisien, du moins c'est mon impression (ils ont des events tout le temps). Qui sait, à terme ils pourront peut-être nous faire des intros business? Ils sont notamment incubé à Paris, chez Legaltech (incubateur legal + tech)
 
Thomas nous a fait une proposition à l'oral, j'ai noté rapidement les choses suivantes:
- Définition de la stratégie RGPD pour ubble
- déclinaison sous la forme d'un pitch commercial différenciant
- déclinaison produit, via un atelier technique avec nos architectes
- déclinaison juridique via la documentation nécessaire (user consent, annexe CGV, autres)
- mise à disposition d'un outil pour générer les registres de traitement, et formation pour sa mise à jour
- Option : PIA (Privacy Impact Assessment)
Budget : 10K€ le tout; 5K€ sans le PIA. 

Ma compréhension est que dans le cadre RGPD, le PIA est obligatoire étant donné la nature de notre business. Je pense donc que ce n'est pas une option. Il nous permettra par ailleurs d'affiner notre stratégie, et de trouver des fondements juridiques clairs à tout ce que nous déclarons faire, et à être au courant de ce que nous faisons en off. Il nous permettra aussi de justifier qu'il n'y a pas d'atteinte, et que nous n'avons pas besoin de faire de déclaration CNIL.

Thomas de Saint-Aubin est à mon avis un homme occupé. Je pense que la valeur de Seraphin est très lié à son expertise à lui. J'aimerais donc m'assurer qu'on aura un Workshop de stratégie avec lui en début de projet - il sera de bons conseils à mon avis pour construire notre stratégie RGPD. 

Pour les déclinaisons on pourra bosser avec ses équipes de juristes / architectes.

En résumé, je pense que cette proposition est honnête. 
Je peux chercher un bench si besoin, mais je pense qu'on pourra pas faire beaucoup mieux... C'est pas cher de l'heure!
Qu'en pensez-vous?

Juliette.

**Comment by francoiswyss** [comment]
Merci Juliette pour le récap.
Ils m'ont fait bonne impression lors du call, et je pense que le budget sera raisonnable. Aussi ça nous aidera à construire un argumentaire commercial super propre et différenciant.
Je n'ai pas eu de retour du galion sur le pricing :(
@juliette-ubbleai si tu as la possibilité de demander autour de toi pour vérifier que c'est une propale raisonnable fais le, mais n'y passe pas trop de temps. Ca me semble fair également!
François

**Comment by juliette-ubbleai** [comment]
J ai demandé à une pote avocate. Elle trouve la propale honnete.
Je vais demander une ou 2 references, et si OK, on y va !
Juliette.

**Comment by juliette-ubbleai** [comment]
Chaude recommandation du regroupement de mutuelle : 

call avec 
Candice Van Lancker
Responsable Education Numérique - ProgEN
Direction des Données et de la Stratégie numérique
M : +33 6 65 14 58 28

- Mise en conformité rgpd est un sujet central pour nous - nous sommes un regroupement de plusieurs mutuelles qui est récent.
- On a des equipes dediées sur ce sujet bien sûr. 
- On a choisit Seraphin pour leur réputation sur le sujet
- Ils sont intervenus sur des aspects de stratégie, de conseil pour nos relations avec la CNIL, de mise en place de process interne, de sensibilisation des équipes, et de rédaction de documentations juridiques
- Thomas est un excellent formateur, il est bon pour vulgariser son expertise, et c'est un des meilleur de la place en conseil en stratégie juridique. C est un vrai spécialiste de la data
- Ils sont tres agiles, le projet s'est tres bien passé, on compte rebosser avec eux. On a eu tous les livrables dans les temps.
