### ISSUE TITLE
Web ou SDK

### ISSUE THREAD

**Issue by francoiswyss** [ubbleai/discussions#3]
Hello,
Je pense qu'il faut clarifier notre discussion sur SDK vs Web App car chacun semble comprendre des choses différentes.

Je distingue 3 codes :

1. Le code de workflow qui détermine à quel moment on appelle le service de vérification, et ce qui se passe quand la vérification est terminée.
2. Le code de guidage de la capture et de la capture en elle même, qui peut être exécuté via une web app ou bien directement sur le téléphone
3. Le code de traitement de la donnée capturée et qui s'exécute dans notre backend

Ceci pose au moins les questions suivantes :

- Comment est géré le code de workflow (sur un site web et sur une app)? 
- Dans le cadre d'une app, le code de workflow semble nécessiter une mise à jour de l'app, même si le code de guidage se fait via une web app. Est-ce bien le cas?
- Est-ce bien dans le code de workflow que l'on détermine si le code de guidage et capture s'exécute en ouvrant un browser en dehors de l'app, ou bien si on peut imposer une web view type interstitiel mais tout en restant dans l'app?
- Faut-il exécuter le code de guidage et capture depuis le téléphone ou bien depuis une web app? Quels sont les avantages en termes de performance et de capacité de personnalisation d'une part, et de facilité d'intégration d'autre part?

**Comment by juliette-ubbleai** [comment]
Est-ce qu'il faudrait pas se faire un petit atelier technique, pour comprendre quelles sont nos grandes options ? je ne suis pas claire sur ce qui est faisable, ce qui se fait le plus en ce moment etc... J'aimerais voir une liste simplifiée des grandes options d'intégration, qu'on en choisisse une et qu'on l'affine.

Les objectifs business étant :
1- Le moins d'effort possible d'intégration côté client
1.1 - démarrage projet
1.2 - mises à jour

2- Un parcours user le plus unifié possible - qu'on ai pas l'impression de sortir de l app ou du site
2.1- idéalement on reste (ou on a l'impression de rester) dans l'app ou sur le site
2.2- notre UI est customizable par client (mise à la charte)
2.3- autre?

3- Un code idéalement unique (ou presque unique), qui permette de gérer les différents canaux
3.1 Site web mobile
3.2 Native app mobile
3.3 Site Web desktop

Juliette

**Comment by ndeber** [comment]
J'ai fait un tableau avec les différents éléments (les 3 codes de François) et les cas possibles.
<img width="881" alt="imagearchitecture" src="https://user-images.githubusercontent.com/3979435/39804656-f09c9c88-5374-11e8-8b76-59cf19a5a7b0.png">

On y retrouve le code "d'integration", géré par le client, qui effectue les appels à notre solution: on est complètement dépendants du client et de sa plateforme (app ou web) et de ses releases. On peut fournir ce code pour faciliter l'intégration. C'est ce code qui décide de la manière de nous appeler, en particulier si nous sommes en web (webview, browser).

Le code "Front-end Ubble", sur lequel on se pose le plus de questions. 4 cas possibles:
- Le client est un site web --> nous aussi en web
- Le client est une app: 3 options pour nous
   - **SDK, intégration dans l'app directement**, comme proposé par Onfido (https://github.com/onfido/onfido-sdk-ui). C'est ce qu'il y aura de plus seamless pour les users, en revanche, c'est des dev spécifiques, un intégration plus lourde et dépendante de chaque client. On aurait accès à toutes les fonctions du téléphone.
   - **Web-View** = simili browser intégré dans l'app (en overlay, ou intégré dans une page). On peut executer le même code que dans un browser (HTML + JS). On garde la main sur notre code, nos releases. C'est encore dans l'app donc plutot seamless pour le user. En revanche, ces webviews ont encore moins de fonctionalités que les browsers (elles sont en retard). Celle qui nous intéresse en priorité est WebRTC pour le streaming:
         - Pour Android, ça doit passer depuis Lollipop (85% des Android) https://fr.wikipedia.org/wiki/Historique_des_versions_d%27Android#/media/File:Android_historical_version_distribution_-_vector.svg et https://developer.chrome.com/multidevice/webview/overview
         - Pour iOS, guess what, c'est plus compliqué et apparement, WebRTC n'est pas encore compatible avec les WebViews iOS - plus précisement l'API GetUserMedia (https://github.com/webrtc/adapter/pull/783)
   - **Web-Browser** = Chrome ou Safari le plus souvent. On se retrouve dans un cas proche du desktop. C'est une rupture pour l'expérience du user (un browser s'ouvre, étrange... on pourrait imaginer brander le site d'arrivée Ubble). On garde la main sur notre code et releases. On a accès à bcp plus de fonctionalités du téléphone, mais pas toutes en particulier sur android (cf. https://caniuse.com/#search=mediarecorder)

Du coup, pour notre "Front-end Ubble":
- l'idéal, ça serait une webview, mais on ne pourra pas y faire ce qu'on souhaite pour l'instant dans iOS et le futur est incertain
- les solutions webview/webbrowser mobile ou desktop tourneront avec un code très similaire, qu'on devra développer de toutes façons
- si les users/clients n'acceptent pas le passage app --> browser, il faudra un sdk iOS...

**Comment by ndeber** [comment]
@francoiswyss je ne suis pas sûr de comprendre ce dont tu parles ici "Le code de guidage de la capture et de la capture en elle même, qui peut être exécuté via une web app ou bien **directement sur le téléphone**" ?

**Comment by gobadiah** [comment]
Je me permet de rajouter une option pour le mobile, qui n’est pas forcément viable aujourd’hui mais ce ne sera pas nécessairement le cas dans le futur. 

Avoir un flow “à la facebook”, lorsque l’on partage certains types de contenus. L’utilisateur est renvoyé sur l’app facebook, effectue le partage, puis est renvoyé sur l’app initial. 

Pros: expérience agréable native agréable pour l’utilisateur, le passage entre app est voué à devenir de plus en plus fluide, contrôle total sur le flow d’identification, indépendamment de l’app client.
Cons: à l’heure actuelle si l’app n’est pas initialement installé, je crois que rien n’est fait pour faciliter son téléchargement, ce qui est rédhibitoire… 

Si jamais dans le futur Apple et Android veulent faciliter ce passage d’app à app (ce qu’ils sont déjà en train de faire), peut-être que ce dernier point sera de moins en moins gênant.

Et puis à terme, vu que de toutes façons Ubble est destiné à devenir la pièce d’identité numérique définitive, l’app sera installé par défaut dans les os dès l’achat.

**Comment by francoiswyss** [comment]
@gobadiah intéressant. Si on est dans tous les smartphones je pense qu'on pourra faire péter le champagne ;)

**Comment by francoiswyss** [comment]
@ndeber peux tu poster le petit récap ici?
La conclusion est que nos clients doivent de toute façon faire une mise à jour de l'app, peu importe si notre code est exécuté via web app (webview ou browser) ou si il est exécuté sur le téléphone via sdk.
-Avantage web app : une petite intégration puis technologie toujours à jour
-Avantage sdk : plus de fonctionnalités disponibles pour la vérification (accès direct ressources téléphone)
A noter que c'est principalement l'UX qui sera du coup toujours à jours car les checks de sécurité se font côté serveur.
