### ISSUE TITLE
Choix Identité visuelle

### ISSUE THREAD

**Issue by juliette-ubbleai** [ubbleai/discussions#5]
Voilà la présentation que Elodie nous a faite cet après midi : [Lien](https://drive.google.com/drive/u/0/folders/1tFSgmtbf0jQYPnKFSvftO-Wy8Hhsn8yJ)

Nous nous sommes accordés en session que nous préférions la proposition 1 et 2, et que nous écartions 3, 4 et 5.
## La proposition 1
**Pros :** le logo est aérien, la police est sympa, typée, on peut jouer avec les dégradés. L'image est moderne, tech, le bleu est rassurant, moderne (il pourrait etre un peu plus peps)
**Cons :** Le smiley est un peu bateau, l'identité / les déclinaisons creusée autour de ce logo ne sont pas très profondes - et je n'ai pas vu beaucoup de potentiel graphique derrière cette identité. La notion de sécurité manque - très axée satisfaction client.

##La proposition 2
**Pros :** le logo transmet bien la notion de sécurité et de crédibilité. C'est sympa d'avoir une mascotte personnifiée, ca rend les choses un peu plus plus fun et moins classique. 
**Cons :** Le logo est complexe, assez massif, pas tres aérien. La facilité d'usage, la tech ressort moins. Il est plus sécuritaire.

J'aurais tendance à privilégier la piste 1, plus classique, plus moderne, plus tech, et qui passera mieux en marque blanche que la 2.
J'aimerais bien lui demander de creuser cette piste, et de développer une identité un peu plus profonde que le smiley, avec une teinte sécurité / une déclinaison plus sécuritaire.

Et vous ?

**Comment by juliette-ubbleai** [comment]
Un autre avantage de la proposition 1, c'est qu'avec le smiley, et son sourire, on peut peut être reprendre cette idée du pont... Du pont entre UX et securité, entre users et Service providers, entre identité physique et identité digitale.

**Comment by francoiswyss** [comment]
Je suis aligné : demandons de creuser la piste 1, avec un hologramme peut être plus visible et de la couleur un peu plus peps.
+ retravailler le smiley.

**Comment by francoiswyss** [comment]
_Qu'est-ce que vous pensez de travailler le point comme un diaphragme d'appareil photo?_
Carrément, super idée!

**Comment by ndeber** [comment]
Retour de Daniel Bo, le boss de Lauren: 

#UBBLE
 
Le nom Ubble sympa et moderne :

- Ubble - able = rendre possible, empowerment
- Hubble = télescope - évoque la technologie, permet de voir loin
- Bubble = bulle

-->beaucoup d’évocations possibles, il faut le resémantiser, lui donner un sens : le sens qu’on sémantise en transformant le U en bouclier, n’est pas le même qu’en interconnectant les deux B.

#LES LOGOS

Le travail global est de très bonne qualité. Ca fait pro, nouvelle économie
Toujours dans l'esprit de marque germinatrice, on aurait besoin de voir au-delà du logo tout ce que ça peut générer. II faut essayer de l’imaginer dès maintenant pour créer un univers cohérent.

##PISTE 1

Intéressante pour sa simplicité et l'ancrage analogique autour des deux yeux (le smiley à l'endroit ou à l'envers suggère l'authentification + ou -). Il y a toute une grammaire, c’est ce qui m’a séduit dans cette piste. Il génère à côté de lui un système ultra simple pour dire que c’est bon ou pas bon. Le dégradé le rend vivant, s’il était monochrome, il serait inerte. Il communique la fluidité, il communique de manière positive sur le transfert.

La forme du smiley n’est pas tirée du U ou du B. Si le smiley est tiré du U on comprendrait mais là c’est un chapeau mais on ne sait pas d’où il vient. Point de validation mais il est petit pour dire la validation : ça veut dire on vous reconnaît à un détail et c’est un peu l’inverse de la réalité. Normalement on valide avec 90-95% de l’info et ici avec la petitesse du point, ça veut dire on vous valide avec 10% de l’info. Le point c’est trop subtil. Il faut montrer l’intégrité de la pièce d’ID. Dans le nom c’est un point final un peu gratuit tandis que dans le logo c’est un œil. Avec le même symbole on arrive à dire on vous regarde et c’est bon. Le smiley qui est une super idée. Point de validation ?

Bleu et violet pâle. Autant le bleu et rouge de la 3 on comprend bien, ce sont des couleurs opposées, on y voit un passage (du début à la fin du processus), autant ici les couleurs sont moins tranchées et il faudrait que cette bichromie soit plus claire : pourquoi ces couleurs ? pourquoi ces proportions (violet sur la toute fin du logo) ? pourquoi si peu de violet dans le nom de base alors que moitié-moitié dans le smiley ? On n’a pas la signification de la bichromie qui est encodée or il faut que le logo encode un message. Pour l’instant c’est juste un nom qui est fluide, il faudrait l’enrichir.

##PISTE 2

La verte évoque peu l'interaction d'identification mais plutôt le blason. Ca évoque l'univers de la sécurité, safeguard, idée de protection, bouclier, culture du safeguard. Protection, coffre-fort. Lettres un peu carrées, rigoureuses. Le personnage de renard on ne voit pas trop ce qu’il veut dire. Voir le rôle qu’il peut jouer : un renard malin ? Après cette histoire de couleur, pourquoi le renard est vert ?

##PISTE 3

La 3 est intéressante pour la symbolique de la transmission riche entre les deux bb qu'on retrouve en signature. Le bleu devient rouge, passer du froid au chaud, il y a un transfert, un changement d'état, c’est intéressant. Il y a cette dimension de transfert, c’est un espèce de jet en sens unique. Et ici le symbole est relié au nom.

 ##PISTE 4

La 4 est intéressante pour l'oeil qui évoque la Webcam mais on ne le retrouve pas directement dans le logo ce qui est dommage car c’est un symbole fort mais il n’est pas identifiable dans le logo. C’est la vue, l’hypervision. Ce qu’il faut symboliser c’est la webcam. C’est un système de validation par webcam. C’est ça qui manque aujourd'hui. Il faut arriver à bien qualifier le service. Ce qu’on met en valeur c’est l’œil de la caméra ? l’œil du client ? l’œil de celui qui vérifie ?

On a plus de mal ici à donner un sens à la chromatique

##PISTE 5

La 5 est un peu sèche, un peu simpliste

**Comment by francoiswyss** [comment]
retour très complet et rassurant, merci.
On avance du coup! Les points à travailler sur le #1 : 
- intensité du dégradé
- couleurs du dégradé
- écrire les lettre A et I pour le .ai
- autre proposition de smiley / élément graphique

**Comment by juliette-ubbleai** [comment]
Hello, 
sur la base du re-travail d'Elodie, je vous propose que nous prenions une décision :) 
Voilà ma proposition de charte graphique finale - qu'en pensez vous ?
- couleurs bleu et violet sombre
- logo ubble. avec un dégradé léger sur le point
- logo ubble.ai avec le ai en bleu
- picto "épais", la première version
- picto seul : dégradés sur les arcs
- picto associé au logo, les arcs en bleu
- picto associé au logo en horizontal : même graisse que le logo, et picto centré
- picto associé au logo en carré : même graisse que le logo
- Typo - les 1ere et 2ème, recommandées par Elodie, sont en effet sympas, mais elles n'ont pas d'italique. Par soucis de simplicité, je vous propose de partir sur l'overpass, qui est plus classique, et qui a tous les styles possibles.

Juliette

**Comment by francoiswyss** [comment]
OK pour moi.

**Comment by ndeber** [comment]
OK pour moi aussi


Le 29 mai 2018 à 11:34:28, Francois-ubbleai (notifications@github.com) a
écrit:

OK pour moi.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ubbleai/discussions/issues/5#issuecomment-392714641>,
or mute the thread
